#!/usr/bin/env sh
#
# Copyright © 2020 nrxr <nrxr@disroot.org> 
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#   THE SOFTWARE.
#
# 
  
PKGS="aws-iam-authenticator awscli blackbox fzf gcc git-extras git-lfs gnupg go htop hugo jq kubernetes-cli kustomize lua mosh mysql nmap pass pgcli postgresql protobuf python-yq r redis rust s3cmd scw stern tarsnap terraform the_silver_searcher tig tree youtube-dl"

RCFILES="fishfiles tmuxfiles nvimfiles gitfiles"

help='
Usage:

manager [-h|--help] # default
manager --version
manager install

Options:

-h --help       Show this help message.
--version       Show the version.
'

version='
Version: 1.0.0
© 2020, nrxr <nrxr@disroot.org>
Released under the MIT license terms.
'

print_version() {
  echo "$version"
}

print_help() {
  echo "$help"
}

checkPreSetup() {
  if [ ! -f pre-setup.sh ]; then
    if command -v curl; then
      curl -OL https://github.com/nrxr/quickconfig/raw/master/pre-setup.sh
    elif command -v wget; then
      wget https://github.com/nrxr/quickconfig/raw/master/pre-setup.sh
    else
      printf "Please, download the file https://github.com/nrxr/quickconfig/raw/master/pre-setup.sh\n"
    fi
  fi

  OS=$(sh ./pre-setup.sh os)
  PM=$(sh ./pre-setup.sh pkm)
}

installFn() {
  checkPreSetup
  sh ./pre-setup.sh setup

  if [ "${PM}" = "brew" ] && [ "${OS}" = "mac" ]; then
      brew install ${PKGS} reattach-to-user-namespace
  elif [ "${PM}" = "xbps" ]; then
    sudo xbps-install -S ${PKGS}
  elif [ "${PM}" = "apk" ]; then
    sudo apk add ${PKGS}
  elif [ "${PM}" = "apt" ]; then
    PKGS=$(echo "${PKGS}" | sed 's/the_silver_searcher/silversearcher-ag/')
    sudo apt install ${PKGS}
  elif [ "${PM}" = "yay" ]; then
    yay -S ${PKGS}
  else
    printf "don't know how to handle your package manager %s" "${PM}"
    exit
  fi

  for i in $RCFILES; do
    mkdir -p "$HOME/code/src/github.com/nrxr"
    if [ ! -d "$HOME/code/src/github.com/nrxr/$i" ]; then
      git clone "https://github.com/nrxr/$i" "$HOME/code/src/github.com/nrxr/$i"
    fi
    cd "$HOME/code/src/github.com/nrxr/$i" && git pull && sh install.sh && cd - || exit
  done
}

main() {
  cmd="$1"
  case "$cmd" in
    -h|--help)        shift; print_help "$@";;
    --version)        shift; print_version "$@";;
    install)          shift; installFn "$@";;
    debug)            shift; checkPreSetup "$@";;
    *)                print_help "$@";;
  esac
}
main "$@"
